# Generated by Django 3.1.2 on 2021-09-11 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='GeneralProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='纲领')),
                ('path', models.CharField(default='', max_length=100, verbose_name='路径')),
                ('ascriptionType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GeneralProgrammes', to='general.ascriptiontype')),
            ],
            options={
                'ordering': ('ascriptionType',),
            },
        ),
        migrations.CreateModel(
            name='LotteryStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default='', verbose_name='日期')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='红球')),
                ('blueBall', models.CharField(blank=True, default='', max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LotteryStages', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名字')),
                ('netPath', models.CharField(default='', max_length=100, verbose_name='网络路径')),
                ('localPath', models.CharField(default='', max_length=100, verbose_name='本地路径')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Categorys', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
