# Generated by Django 3.1.2 on 2021-09-28 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='GeneralProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='纲领')),
                ('type', models.CharField(default='', max_length=100, verbose_name='图标类型')),
                ('reptile', models.CharField(default='', max_length=100, verbose_name='爬虫地址')),
                ('ascriptionType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GeneralProgrammes', to='general.ascriptiontype')),
            ],
            options={
                'ordering': ('ascriptionType',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redBallNum', models.IntegerField(default=0, verbose_name='红球数量')),
                ('redBallMaxValue', models.IntegerField(default=0, verbose_name='红球最大值')),
                ('blueBallNum', models.IntegerField(default=0, verbose_name='蓝球数量')),
                ('blueBallMaxValue', models.IntegerField(default=0, verbose_name='蓝球最大值')),
                ('ascription', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Rule', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('ascription',),
            },
        ),
        migrations.CreateModel(
            name='LotteryStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('time', models.CharField(blank=True, default='', help_text='开奖日期（CharField）', max_length=20, verbose_name='开奖日期')),
                ('redBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LotteryStages', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('-IssueNumber',),
            },
        ),
        migrations.CreateModel(
            name='KillNumberRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='杀号方法名')),
                ('object', models.IntegerField(default=0, verbose_name='杀号对象')),
                ('format', models.CharField(default='', max_length=100, verbose_name='杀号格式')),
                ('param', models.CharField(default='', max_length=100, verbose_name='杀号参数')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumberRules', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KillNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(default=[], max_length=256, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumbers', to='general.generalprogramme')),
                ('lotteryStage', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumber', to='general.lotterystage')),
            ],
            options={
                'ordering': ('-IssueNumber',),
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Forecasts', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('IssueNumber',),
            },
        ),
        migrations.CreateModel(
            name='ColdAndHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(default=[], max_length=255, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ColdAndHots', to='general.generalprogramme')),
                ('lotteryStage', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ColdAndHot', to='general.lotterystage')),
            ],
            options={
                'ordering': ('-IssueNumber',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名字')),
                ('type', models.CharField(default='', max_length=100, verbose_name='图标类型')),
                ('netPath', models.CharField(default='', max_length=100, verbose_name='网络路径')),
                ('localPath', models.CharField(default='', max_length=100, verbose_name='本地路径')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Categorys', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
