# Generated by Django 3.1.2 on 2021-09-11 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterystage',
            name='blueBall',
            field=models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球'),
        ),
        migrations.AlterField(
            model_name='lotterystage',
            name='redBall',
            field=models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='红球'),
        ),
    ]
