# Generated by Django 3.1.2 on 2021-09-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210911_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotterystage',
            options={'ordering': ('IssueNumber',)},
        ),
        migrations.RemoveField(
            model_name='lotterystage',
            name='time',
        ),
    ]
