# Generated by Django 3.1.2 on 2021-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_lotterystage_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterystage',
            name='Balance',
            field=models.BigIntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='lotterystage',
            name='MoneyBalance',
            field=models.BigIntegerField(default=0, verbose_name='金钱差额'),
        ),
    ]
