# Generated by Django 3.1.2 on 2021-09-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210912_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprogramme',
            name='path',
        ),
    ]
