# Generated by Django 3.1.2 on 2021-10-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210930_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
