# Generated by Django 3.1.2 on 2021-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_delete_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(default='', max_length=100, verbose_name='歌手')),
                ('duration', models.IntegerField(default=0, verbose_name='时长')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
            ],
            options={
                'ordering': ('singer',),
            },
        ),
    ]
