# Generated by Django 3.1.2 on 2021-09-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_generalprogramme_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='图标类型'),
        ),
        migrations.AddField(
            model_name='generalprogramme',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='图标类型'),
        ),
    ]
