# Generated by Django 3.1.2 on 2021-10-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lrc',
            field=models.CharField(default='', max_length=100, verbose_name='歌词'),
        ),
        migrations.AddField(
            model_name='song',
            name='pic',
            field=models.CharField(default='', max_length=100, verbose_name='封面地址'),
        ),
        migrations.AddField(
            model_name='song',
            name='theme',
            field=models.CharField(default='', max_length=100, verbose_name='歌词'),
        ),
    ]
