# Generated by Django 3.1.2 on 2021-09-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20210914_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redBallNum', models.IntegerField(default=0, verbose_name='红球数量')),
                ('redBallMaxValue', models.IntegerField(default=0, verbose_name='红球最大值')),
                ('blueBallNum', models.IntegerField(default=0, verbose_name='蓝球数量')),
                ('blueBallMaxValue', models.IntegerField(default=0, verbose_name='蓝球最大值')),
                ('ascription', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Rule', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('ascription',),
            },
        ),
    ]
