# Generated by Django 3.1.2 on 2021-10-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20211008_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='theme',
            field=models.CharField(default='', max_length=100, verbose_name='主题色'),
        ),
    ]
