# Generated by Django 3.1.2 on 2021-09-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotterystage',
            options={'ordering': ('-IssueNumber',)},
        ),
    ]
