# Generated by Django 3.1.2 on 2021-09-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20210915_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterystage',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
