# Generated by Django 3.1.2 on 2021-10-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20211008_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('artist',)},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='address',
            new_name='src',
        ),
    ]
