# Generated by Django 3.1.2 on 2021-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20210916_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterystage',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
