# Generated by Django 3.1.2 on 2021-10-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20211008_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
