# Generated by Django 3.1.2 on 2021-09-16 02:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20210916_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Forecasts', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('IssueNumber',),
            },
        ),
    ]
