# Generated by Django 3.1.2 on 2021-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='blueBall',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='redBall',
            field=models.JSONField(null=True),
        ),
    ]
