# Generated by Django 3.1.2 on 2021-09-16 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20210916_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldandhot',
            name='redBall',
            field=models.CharField(default=[], max_length=255, validators=[django.core.validators.int_list_validator], verbose_name='红球'),
        ),
    ]
