# Generated by Django 3.1.2 on 2021-09-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20210916_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldandhot',
            options={'ordering': ('-IssueNumber',)},
        ),
        migrations.AddField(
            model_name='generalprogramme',
            name='reptile',
            field=models.CharField(default='', max_length=100, verbose_name='爬虫地址'),
        ),
    ]
