# Generated by Django 3.1.2 on 2021-09-19 04:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20210918_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueNumber', models.IntegerField(default='', verbose_name='期号')),
                ('redBall', models.CharField(default=[], max_length=255, validators=[django.core.validators.int_list_validator], verbose_name='红球')),
                ('blueBall', models.CharField(default=[], max_length=255, validators=[django.core.validators.int_list_validator], verbose_name='蓝球')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumbers', to='general.generalprogramme')),
            ],
            options={
                'ordering': ('-IssueNumber',),
            },
        ),
        migrations.CreateModel(
            name='KillNumberRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='杀号方法名')),
                ('method', models.CharField(default='', max_length=100, verbose_name='杀号方法')),
                ('ascription', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumberRule', to='general.killnumber')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
