# Generated by Django 3.1.2 on 2021-09-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_killnumber_killnumberrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killnumberrule',
            name='ascription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumberRules', to='general.killnumber'),
        ),
    ]
