# Generated by Django 3.1.2 on 2021-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20210919_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='killnumberrule',
            name='object',
            field=models.IntegerField(default=0, verbose_name='杀号对象'),
        ),
    ]
