# Generated by Django 3.1.2 on 2021-09-20 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_killnumberrule_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killnumber',
            name='redBall',
            field=models.CharField(default=[], max_length=512, validators=[django.core.validators.int_list_validator], verbose_name='红球'),
        ),
    ]
