# Generated by Django 3.1.2 on 2021-09-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_auto_20210920_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='killnumber',
            name='lotteryStage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lotteryStage', to='general.lotterystage'),
        ),
    ]
