# Generated by Django 3.1.2 on 2021-09-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_killnumber_lotterystage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldandhot',
            name='lotteryStage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ColdAndHot', to='general.lotterystage'),
        ),
        migrations.AlterField(
            model_name='killnumber',
            name='lotteryStage',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumber', to='general.lotterystage'),
        ),
    ]
