# Generated by Django 3.1.2 on 2021-09-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_auto_20210922_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killnumber',
            name='lotteryStage',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='KillNumber', to='general.lotterystage'),
        ),
    ]
